-- 이탈율 분석 
-- 회원 탈퇴 등의 적극적 행동은 데이터에 존재하지 않음
-- 일정 기간을 설정해서 더 이상 구매가 일어나지 않은 고객을 이탈 고객으로 파악

SELECT * FROM ORDER_PRODUCT_ITEMS_CUS;

-- 주문 날짜가 가장 빠른 일자와 가장 최근 일자 : 2017-10-03 / 2019-07-30

SELECT MIN(ORDER_PURCHASE_TIMESTAMP), MAX(ORDER_PURCHASE_TIMESTAMP)
FROM ORDER_PRODUCT_ITEMS_CUS;

-- 현재 날짜를 2019년 8월 1일로 가정, 최근 6개월 내 구매한 고객 중에서 최근 3개월 내 구매하지 않은 고객 이탈율
-- CHURNED_CUSTOMERS_COUNT : 20,199 / RECENT_PURCHASES_COUNT : 37,007 / CHURN_RATE : 54.6%

WITH RECENT_PURCHASES AS (
    SELECT DISTINCT CUSTOMER_ID
    FROM ORDER_PRODUCT_ITEMS_CUS
    WHERE ORDER_PURCHASE_TIMESTAMP BETWEEN '2019-02-01' AND '2019-07-31'
), CHURNED_CUSTOMERS AS (
    SELECT DISTINCT CUSTOMER_ID
    FROM RECENT_PURCHASES
    WHERE CUSTOMER_ID NOT IN (
        SELECT DISTINCT CUSTOMER_ID
        FROM ORDER_PRODUCT_ITEMS_CUS
        WHERE ORDER_PURCHASE_TIMESTAMP BETWEEN '2019-05-01' AND '2019-07-31')
)
SELECT 
	(SELECT COUNT(*) FROM CHURNED_CUSTOMERS) AS CHURNED_CUSTOMER_COUNT,
    (SELECT COUNT(*) FROM RECENT_PURCHASES) AS RECENT_PURCHASE_COUNT,
    (SELECT COUNT(*) FROM CHURNED_CUSTOMERS) * 100.0 / 
    (SELECT COUNT(*) FROM RECENT_PURCHASES) AS CHURN_RATE;

-- 현재 날짜를 2019년 8월 1일로 가정, 최근 1년 내 구매한 고객 중에서 최근 6개월 내 구매하지 않은 고객 이탈율
-- CHURNED_CUSTOMERS_COUNT : 32,437 / RECENT_PURCHASES_COUNT : 69,444 / CHURN_RATE : 46.7%

WITH RECENT_PURCHASES AS (
    SELECT DISTINCT CUSTOMER_ID
    FROM ORDER_PRODUCT_ITEMS_CUS
    WHERE ORDER_PURCHASE_TIMESTAMP BETWEEN '2018-08-01' AND '2019-07-31'
), CHURNED_CUSTOMERS AS (
    SELECT DISTINCT CUSTOMER_ID
    FROM RECENT_PURCHASES
    WHERE CUSTOMER_ID NOT IN (
        SELECT DISTINCT CUSTOMER_ID
        FROM ORDER_PRODUCT_ITEMS_CUS
        WHERE ORDER_PURCHASE_TIMESTAMP BETWEEN '2019-02-01' AND '2019-07-31')
)
SELECT 
	(SELECT COUNT(*) FROM CHURNED_CUSTOMERS) AS CHURNED_CUSTOMER_COUNT,
    (SELECT COUNT(*) FROM RECENT_PURCHASES) AS RECENT_PURCHASE_COUNT,
    (SELECT COUNT(*) FROM CHURNED_CUSTOMERS) * 100.0 / 
    (SELECT COUNT(*) FROM RECENT_PURCHASES) AS CHURN_RATE;

-- 현재 날짜를 2019년 8월 1일로 가정, 최근 1년 내 구매한 고객 중에서 최근 3개월 내 구매하지 않은 고객 이탈율
-- CHURNED_CUSTOMERS_COUNT : 52,636 / RECENT_PURCHASES_COUNT : 69,444 / CHURN_RATE : 75.8%

WITH RECENT_PURCHASES AS (
    SELECT DISTINCT CUSTOMER_ID
    FROM ORDER_PRODUCT_ITEMS_CUS
    WHERE ORDER_PURCHASE_TIMESTAMP BETWEEN '2018-08-01' AND '2019-07-31'
), CHURNED_CUSTOMERS AS (
    SELECT DISTINCT CUSTOMER_ID
    FROM RECENT_PURCHASES
    WHERE CUSTOMER_ID NOT IN (
        SELECT DISTINCT CUSTOMER_ID
        FROM ORDER_PRODUCT_ITEMS_CUS
        WHERE ORDER_PURCHASE_TIMESTAMP BETWEEN '2019-05-01' AND '2019-07-31')
)
SELECT 
	(SELECT COUNT(*) FROM CHURNED_CUSTOMERS) AS CHURNED_CUSTOMER_COUNT,
    (SELECT COUNT(*) FROM RECENT_PURCHASES) AS RECENT_PURCHASE_COUNT,
    (SELECT COUNT(*) FROM CHURNED_CUSTOMERS) * 100.0 / 
    (SELECT COUNT(*) FROM RECENT_PURCHASES) AS CHURN_RATE;

-- 현재 날짜를 2019년 8월 1일로 가정, 가입해서 구매한 고객 중 최근 6개월 내 구매하지 않은 고객 이탈율
-- CHURNED_CUSTOMERS_COUNT : 50,341 / RECENT_PURCHASES_COUNT : 87,348 / CHURN_RATE : 57.6%

WITH RECENT_PURCHASES AS (
    SELECT DISTINCT CUSTOMER_ID
    FROM ORDER_PRODUCT_ITEMS_CUS
    WHERE ORDER_PURCHASE_TIMESTAMP BETWEEN '2017-10-03' AND '2019-07-31'
), CHURNED_CUSTOMERS AS (
    SELECT DISTINCT CUSTOMER_ID
    FROM RECENT_PURCHASES
    WHERE CUSTOMER_ID NOT IN (
        SELECT DISTINCT CUSTOMER_ID
        FROM ORDER_PRODUCT_ITEMS_CUS
        WHERE ORDER_PURCHASE_TIMESTAMP BETWEEN '2019-02-01' AND '2019-07-31')
)
SELECT 
	(SELECT COUNT(*) FROM CHURNED_CUSTOMERS) AS CHURNED_CUSTOMER_COUNT,
    (SELECT COUNT(*) FROM RECENT_PURCHASES) AS RECENT_PURCHASE_COUNT,
    (SELECT COUNT(*) FROM CHURNED_CUSTOMERS) * 100.0 / 
    (SELECT COUNT(*) FROM RECENT_PURCHASES) AS CHURN_RATE;

-- 현재 날짜를 2019년 8월 1일로 가정, 가입해서 구매한 고객 중 최근 3개월 내 구매하지 않은 고객 이탈율
-- CHURNED_CUSTOMERS_COUNT : 70,540 / RECENT_PURCHASES_COUNT : 87,348 / CHURN_RATE : 80.8%

WITH RECENT_PURCHASES AS (
    SELECT DISTINCT CUSTOMER_ID
    FROM ORDER_PRODUCT_ITEMS_CUS
    WHERE ORDER_PURCHASE_TIMESTAMP BETWEEN '2017-10-03' AND '2019-07-31'
), CHURNED_CUSTOMERS AS (
    SELECT DISTINCT CUSTOMER_ID
    FROM RECENT_PURCHASES
    WHERE CUSTOMER_ID NOT IN (
        SELECT DISTINCT CUSTOMER_ID
        FROM ORDER_PRODUCT_ITEMS_CUS
        WHERE ORDER_PURCHASE_TIMESTAMP BETWEEN '2019-05-01' AND '2019-07-31')
)
SELECT 
	(SELECT COUNT(*) FROM CHURNED_CUSTOMERS) AS CHURNED_CUSTOMER_COUNT,
    (SELECT COUNT(*) FROM RECENT_PURCHASES) AS RECENT_PURCHASE_COUNT,
    (SELECT COUNT(*) FROM CHURNED_CUSTOMERS) * 100.0 / 
    (SELECT COUNT(*) FROM RECENT_PURCHASES) AS CHURN_RATE;


---------- 정리 ----------

-- 이탈 고객들을 다시 돌아오게 할 전략이 필요
-- 가입해서 구매한 고객 중 최근 3개월 내 구매하지 않은 고객 이탈율 : 이탈율이 상당히 높음(80%)
-- 최근 1년 내 구매한 고객 중에서 최근 3개월 내 구매하지 않은 고객 이탈율 : 이탈율이 상당히 높음(75.8%)
-- 가입해서 구매한 고객 중 최근 6개월 내 구매하지 않은 고객 이탈율 : 이탈율이 다소 낮음(57%)
-- 최근 6개월 내 구매한 고객 중에서 최근 3개월 내 구매하지 않은 고객 이탈율 : 이탈율이 다소 낮음(54%)
-- 최근 1년 내 구매한 고객 중에서 최근 6개월 내 구매하지 않은 고객 : 이탈율은 다소 낮음(46%)

-- 최근 3개월간 구매하지 않은 고객들에게 특별히 프로모션을 진행할 필요성이 있음
-- 최근 3개월간 쇼핑몰의 정책이나 UI나 결제 방식 등등 바뀐 것이 불편함을 가져오지는 않았는지 검토 필요


