SELECT * FROM ORDER_PRODUCT_ITEMS_CUS;

--------- 1. 고객의 주문 수를 기준으로 한 전환율 분석 ----------

-- 전체 고객 수 : 87,348명

SELECT COUNT(DISTINCT CUSTOMER_ID) 
FROM ORDER_PRODUCT_ITEMS_CUS;

-- 고객 중 재구매한 고객 : 9,202명

SELECT CUSTOMER_ID, COUNT(CUSTOMER_ID) AS COUNT_CUS
FROM ORDER_PRODUCT_ITEMS_CUS
GROUP BY CUSTOMER_ID
HAVING COUNT(CUSTOMER_ID) > 1;

-- 첫구매에서 재구매로의 전환율 : 10.53%

WITH REPEAT_CUSTOMERS AS (
    SELECT CUSTOMER_ID
    FROM ORDER_PRODUCT_ITEMS_CUS
    GROUP BY CUSTOMER_ID
    HAVING COUNT(CUSTOMER_ID) > 1
)
SELECT 
    (SELECT COUNT(*) FROM REPEAT_CUSTOMERS) * 100.0 / 
    (SELECT COUNT(DISTINCT CUSTOMER_ID) FROM ORDER_PRODUCT_ITEMS_CUS) AS REPEAT_PURCHASE_RATE;

-- 고객 중 세번 구매한 고객 : 2,087명

SELECT CUSTOMER_ID, COUNT(CUSTOMER_ID) AS COUNT_CUS
FROM ORDER_PRODUCT_ITEMS_CUS
GROUP BY CUSTOMER_ID
HAVING COUNT(CUSTOMER_ID) > 2;

-- 재구매에서 세번째 구매로의 전환율 : 22.68%

WITH SECOND_PURCHASE_CUSTOMERS AS (
    SELECT CUSTOMER_ID
    FROM ORDER_PRODUCT_ITEMS_CUS
    GROUP BY CUSTOMER_ID
    HAVING COUNT(CUSTOMER_ID) > 1
), THIRD_PURCHASE_CUSTOMERS AS (
    SELECT CUSTOMER_ID
    FROM ORDER_PRODUCT_ITEMS_CUS
    GROUP BY CUSTOMER_ID
    HAVING COUNT(CUSTOMER_ID) > 2
)
SELECT 
    (SELECT COUNT(*) FROM THIRD_PURCHASE_CUSTOMERS) * 100.0 / 
    (SELECT COUNT(*) FROM SECOND_PURCHASE_CUSTOMERS) AS SECOND_TO_THIRD_PURCHASE_RATE;

-- 네번 이상 구매한 고객 : 911명

SELECT CUSTOMER_ID, COUNT(CUSTOMER_ID) AS COUNT_CUS
FROM ORDER_PRODUCT_ITEMS_CUS
GROUP BY CUSTOMER_ID
HAVING COUNT(CUSTOMER_ID) > 3;

-- 세번째 구매에서 네번째 구매로의 전환율 : 43.54%

WITH THIRD_PURCHASE_CUSTOMERS AS (
    SELECT CUSTOMER_ID
    FROM ORDER_PRODUCT_ITEMS_CUS
    GROUP BY CUSTOMER_ID
    HAVING COUNT(CUSTOMER_ID) > 2
), FOURTH_PURCHASE_CUSTOMERS AS (
    SELECT CUSTOMER_ID
    FROM ORDER_PRODUCT_ITEMS_CUS
    GROUP BY CUSTOMER_ID
    HAVING COUNT(CUSTOMER_ID) > 3
)
SELECT 
    (SELECT COUNT(*) FROM FOURTH_PURCHASE_CUSTOMERS) * 100.0 / 
    (SELECT COUNT(*) FROM THIRD_PURCHASE_CUSTOMERS) AS SECOND_TO_THIRD_PURCHASE_RATE;

-------- 정리 ---------

-- 첫구매에서 재구매로 전환되는 비율이 가장 낮음.
-- 첫 구매 경험을 개선하여 재구매율을 높여야 함.
-- 첫 구매 후 고객 만족도를 높이는 방법이 요구됨.

-- 두번째 구매에서 세번째 구매로 전환되는 비율도 더 높여야 함.
-- 재구매 고객을 대상으로 한 마케팅 전략이 필요함.

-- 세번째 구매에서 네번째 구매를 하는 고객들은 충성도가 높은 고객.
-- 이들만을 위한 특별한 관리 시스템 및 이벤트를 실행하면 좋을 듯.


---------- 2. 리뷰 점수를 기준으로 한 재구매 전환율 분석 ----------

-- 리뷰 점수의 분포 확인 : 5점(57%) > 4점(11%) > 1점(11%) > 3점(8%) > 2점(3%) 

SELECT 
    REVIEW_SCORE, 
    COUNT(*) AS SCORE_COUNT, 
    COUNT(*) * 100.0 / (SELECT COUNT(*) FROM ORDER_PRODUCT_ITEMS_CUS) AS SCORE_PERCENTAGE
FROM ORDER_PRODUCT_ITEMS_CUS
GROUP BY REVIEW_SCORE
ORDER BY REVIEW_SCORE;

-- 4점과 5점을 준 사람들의 재구매로의 전환율 : 8.7%

WITH HIGH_STAR_CUSTOMERS AS (
    SELECT DISTINCT CUSTOMER_ID
    FROM ORDER_PRODUCT_ITEMS_CUS
    WHERE REVIEW_SCORE IN (4, 5)
), REPEAT_PURCHASE_CUSTOMERS AS (
    SELECT CUSTOMER_ID
    FROM ORDER_PRODUCT_ITEMS_CUS
    GROUP BY CUSTOMER_ID
    HAVING COUNT(CUSTOMER_ID) > 1
)
SELECT 
    (SELECT COUNT(*) FROM REPEAT_PURCHASE_CUSTOMERS WHERE CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM HIGH_STAR_CUSTOMERS)) * 100.0 / 
    (SELECT COUNT(*) FROM HIGH_STAR_CUSTOMERS) AS HIGH_STAR_REPEAT_PURCHASE_RATE;

-- 1점을 준 사람들의 재구매로의 전환율 : 22.58%

WITH LOW_STAR_CUSTOMERS AS (
    SELECT DISTINCT CUSTOMER_ID
    FROM ORDER_PRODUCT_ITEMS_CUS
    WHERE REVIEW_SCORE = 1
), REPEAT_PURCHASE_CUSTOMERS AS (
    SELECT CUSTOMER_ID
    FROM ORDER_PRODUCT_ITEMS_CUS
    GROUP BY CUSTOMER_ID
    HAVING COUNT(CUSTOMER_ID) > 1
)
SELECT 
    (SELECT COUNT(*) FROM REPEAT_PURCHASE_CUSTOMERS WHERE CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM LOW_STAR_CUSTOMERS)) * 100.0 / 
    (SELECT COUNT(*) FROM LOW_STAR_CUSTOMERS) AS LOW_STAR_REPEAT_PURCHASE_RATE;

-- 2점과 3점을 준 사람들의 재구매로의 전환율 : 13.99%

WITH MID_STAR_CUSTOMERS AS (
    SELECT DISTINCT CUSTOMER_ID
    FROM ORDER_PRODUCT_ITEMS_CUS
    WHERE REVIEW_SCORE IN (2, 3)
), REPEAT_PURCHASE_CUSTOMERS AS (
    SELECT CUSTOMER_ID
    FROM ORDER_PRODUCT_ITEMS_CUS
    GROUP BY CUSTOMER_ID
    HAVING COUNT(CUSTOMER_ID) > 1
)
SELECT 
    (SELECT COUNT(*) FROM REPEAT_PURCHASE_CUSTOMERS WHERE CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM MID_STAR_CUSTOMERS)) * 100.0 / 
    (SELECT COUNT(*) FROM MID_STAR_CUSTOMERS) AS MID_STAR_REPEAT_PURCHASE_RATE;

-------- 정리 ---------

-- 5점이 가장 많음 : 상품 홍보에 사용하기 좋음.
-- 하지만 4점과 5점을 준 고객들의 재구매 전환율은 가장 낮음. 그 이유를 분석해야 함.
-- 1점을 준 고객들의 재구매 전환율이 22.58%로 가장 높음.
-- 고객 만족도가 낮아도 재구매율이 높을 수 있음.

