-- 판매자들의 수익을 높이면 쇼핑몰의 전체 수익도 증대 (수수료 증가 기대) 

-- 판매 현황 및 주요 성과 지표부터 검토

SELECT * FROM ORDER_ITEMS;

SELECT * FROM ORDERS;

SELECT * FROM CUSTOMERS;

SELECT * FROM PRODUCTS;

SELECT * FROM REVIEWS;

-- 판매자들이 몇 명이나 존재하는지

SELECT 
    COUNT(SELLER_ID) AS TOTAL_SELLER_ID,
    COUNT(DISTINCT SELLER_ID) AS UNIQUE_SELLER_ID
FROM ORDER_ITEMS;

-- 판매자들의 판매금액(매출액)과 판매량 확인

SELECT SUM(PRICE), SELLER_ID, COUNT(SELLER_ID)
FROM ORDER_ITEMS
GROUP BY SELLER_ID
ORDER BY SUM(PRICE) DESC;

-- 자주 사용하게 될 조인 테이블이므로 뷰로 만들기

CREATE VIEW ORDER_PRODUCT_ITEMS_CUS AS
SELECT 
    O.ORDER_ID,
	ORD.ORDER_PURCHASE_TIMESTAMP,
    O.SELLER_ID,
    P.PRODUCT_ID AS P_PRODUCT_ID,
    P.PRODUCT_CATEGORY_NAME,
    O.PRICE,
    O.FREIGHT_VALUE,
    ORD.CUSTOMER_ID,
    C.CUSTOMER_STATE,
	R.REVIEW_ID,
	R.REVIEW_SCORE
FROM ORDER_ITEMS O
JOIN PRODUCTS P ON O.PRODUCT_ID = P.PRODUCT_ID
JOIN ORDERS ORD ON O.ORDER_ID = ORD.ORDER_ID
JOIN CUSTOMERS C ON ORD.CUSTOMER_ID = C.CUSTOMER_ID
JOIN REVIEWS R ON ORD.ORDER_ID = R.ORDER_ID
ORDER BY O.ORDER_ID;

-- 뷰 확인

SELECT * FROM ORDER_PRODUCT_ITEMS_CUS;

-- 가장 판매금액(매출액)이 많은 사람부터

SELECT SUM(PRICE), SELLER_ID, COUNT(SELLER_ID)
FROM ORDER_PRODUCT_ITEMS_CUS
GROUP BY SELLER_ID
ORDER BY SUM(PRICE) DESC;

-- 가장 판매량이 많은 사람부터

SELECT SUM(PRICE), SELLER_ID, COUNT(SELLER_ID)
FROM ORDER_PRODUCT_ITEMS_CUS
GROUP BY SELLER_ID
ORDER BY COUNT(SELLER_ID) DESC;

-- 판매자들이 판매하는 품목의 종류 수

SELECT SELLER_ID, COUNT(DISTINCT PRODUCT_CATEGORY_NAME) AS CATEGORY_COUNT, SUM(PRICE)
FROM ORDER_PRODUCT_ITEMS_CUS
GROUP BY SELLER_ID
ORDER BY CATEGORY_COUNT DESC;

-- 판매자별로 베스트셀러 품목 하나씩만 제시(*구매 건수 기준으로는 같은 COUNT수가 존재해서 여러 개의 품목이 추출되는 판매자가 존재함)

SELECT SELLER_ID, PRODUCT_CATEGORY_NAME, ORDER_COUNT
FROM (
    SELECT SELLER_ID, PRODUCT_CATEGORY_NAME, COUNT(ORDER_ID) AS ORDER_COUNT,
           RANK() OVER (PARTITION BY SELLER_ID ORDER BY COUNT(ORDER_ID) DESC) AS R
    FROM ORDER_PRODUCT_ITEMS_CUS
    GROUP BY SELLER_ID, PRODUCT_CATEGORY_NAME
) RANKED
WHERE R = 1;

-- 판매자별로 베스트셀러 품목 하나씩만 제시(해당 품목 매출액 기준)

SELECT SELLER_ID, PRODUCT_CATEGORY_NAME, TOTAL_REVENUE
FROM (
    SELECT SELLER_ID, PRODUCT_CATEGORY_NAME, SUM(PRICE) AS TOTAL_REVENUE,
           ROW_NUMBER() OVER (PARTITION BY SELLER_ID ORDER BY SUM(PRICE) DESC) AS R
    FROM ORDER_PRODUCT_ITEMS_CUS
    GROUP BY SELLER_ID, PRODUCT_CATEGORY_NAME
) RANKED
WHERE R = 1;

-- 판매자별로 매출이 저조한 품목 하나씩만 제시(*구매 건수 기준으로는 같은 COUNT수가 존재해서 여러 개의 품목이 추출되는 판매자가 존재함)

SELECT SELLER_ID, PRODUCT_CATEGORY_NAME, ORDER_COUNT
FROM (
    SELECT SELLER_ID, PRODUCT_CATEGORY_NAME, COUNT(ORDER_ID) AS ORDER_COUNT,
           RANK() OVER (PARTITION BY SELLER_ID ORDER BY COUNT(ORDER_ID) ASC) AS R
    FROM ORDER_PRODUCT_ITEMS_CUS
    GROUP BY SELLER_ID, PRODUCT_CATEGORY_NAME
) RANKED
WHERE R = 1;

-- 판매자별로 매출이 저조한 품목 하나씩만 제시(판매금액 기준)

SELECT SELLER_ID, PRODUCT_CATEGORY_NAME, TOTAL_REVENUE
FROM (
    SELECT SELLER_ID, PRODUCT_CATEGORY_NAME, SUM(PRICE) AS TOTAL_REVENUE,
           ROW_NUMBER() OVER (PARTITION BY SELLER_ID ORDER BY SUM(PRICE) ASC) AS R
    FROM ORDER_PRODUCT_ITEMS_CUS
    GROUP BY SELLER_ID, PRODUCT_CATEGORY_NAME
) RANKED
WHERE R = 1;

-- 판매자별 고객 수

SELECT SELLER_ID, COUNT(DISTINCT CUSTOMER_ID) AS CUSTOMER_COUNT
FROM ORDER_PRODUCT_ITEMS_CUS
GROUP BY SELLER_ID
ORDER BY CUSTOMER_COUNT DESC;

-- 판매자별 상품 수 

SELECT SELLER_ID, COUNT(DISTINCT P_PRODUCT_ID) AS PRODUCT_COUNT
FROM ORDER_PRODUCT_ITEMS_CUS
GROUP BY SELLER_ID
ORDER BY PRODUCT_COUNT DESC;

-- 한 판매자에게 한 고객이 몇 번이나 주문했는지 확인 (결과 : 모두 1번씩만 주문함)

SELECT 
    SELLER_ID,
    CUSTOMER_ID,
    COUNT(DISTINCT ORDER_ID) AS ORDER_COUNT
FROM ORDER_PRODUCT_ITEMS_CUS
GROUP BY SELLER_ID, CUSTOMER_ID
ORDER BY SELLER_ID, CUSTOMER_ID;

-- 주문 건당 평균 판매 금액 : 평균 금액 기준으로

SELECT SELLER_ID, 
	   COUNT(ORDER_ID),
       ROUND(SUM(PRICE) / COUNT(DISTINCT ORDER_ID), 2) AS AVG_SALE_PER_ORDER
FROM ORDER_PRODUCT_ITEMS_CUS
GROUP BY SELLER_ID
ORDER BY AVG_SALE_PER_ORDER DESC;

--주문 건당 평균 판매 금액 : 주문 건수 기준으로
 
SELECT SELLER_ID, 
	   COUNT(ORDER_ID),
       ROUND(SUM(PRICE) / COUNT(DISTINCT ORDER_ID), 2) AS AVG_SALE_PER_ORDER
FROM ORDER_PRODUCT_ITEMS_CUS
GROUP BY SELLER_ID
ORDER BY COUNT(ORDER_ID) DESC;

-- 판매자별 리뷰 평점

SELECT 
    SELLER_ID,
    ROUND(AVG(REVIEW_SCORE),2) AS AVG_REVIEW_SCORE
FROM ORDER_PRODUCT_ITEMS_CUS
GROUP BY SELLER_ID;
